---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"
    username: 
     - webuser1
     - webuser2
    packages:
     - git
     - sendmail
   
  tasks:

  - name: create multiple user
    ansible.builtin.user: 
      name: "{{ item }}"
      group: software
      state: present
    loop: "{{ username }}"  

  - name: install packages
    ansible.builtin.yum:
      name: "{{ packages }}"
      state: present