---
# playbook with items
- hosts: webserver
  become: yes  
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ans_pwd}}"
    vars:
     user_data:
      - user0
      - user5

  tasks:
  - name: creating user
    ansible.builtin.user:
    name: "{{item}}"
    
  - name: using with items
    ansible.builtin.debug:
     msg: "{{ items}}"
    with_items: "{{ user_data }}" 