---

- name: install httpd package
  ansible.builtin.yum:
    name: httpd
    state: present

- name: restart the service
  ansible.builtin.service:
    name: httpd
    state: restarted    

- name: using linux commands
  ansible.builtin.shell: 
    name: cat /etc/passwd
    register: output

- name: checking output value
  ansible.builtin.debug:
    msg: "{{output}}"

