---
#condition demo
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"

  tasks:
  - name: checking ansible facts
    ansible.builtin.debug:
     vars: ansible_facts
     register: output

  - name: checking ansible facts of os family
    ansible.builtin.debug:
     msg: "{{ ansible_facts['os family'] }}"
     
