---
#until condition on user module
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"

  tasks:
  - name: creating user with until condition
    ansible.builtin.shell: useradd gorv -u 130990 -s /bin/bash 
    register: output
    until: output.rc == 0
    retries: 4
    delay: 2

  - name: checking output
    ansible.builtin.debug:
     msg: "{{ output }}"  