---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: checking user exits on server
    ansible.builtin.shell: cat /etc/passwd | grep -i user2
    register: output


  - name: checking the value for output
    ansible.builtin.debug:
      msg: "{{output}}"

  - name: include role (dynamic role) 
    include_role:
      name: httpd_roles

  