---
# dictionary iteration loop
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"

  tasks:
  - name: Using dict2items
    ansible.builtin.debug:
       msg: "{{ item.key }} - {{ item.value }}"
    loop: "{{ tag_data | dict2items }}"
    vars:
      tag_data:
        Environment: dev
        Application: payment  
 