---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
  ansible_connection: ssh
  ansible_user: lnxserver01
  ansible_root: "{{hello}}"
  username: 
  - webuser1
  - webuser2
  packages:
   - git
   - sendmail
   
  tasks:

  - name: create multiple user
    ansible.builtin.user: 
      name: "{{item}}"
      uid: 1345
      group: software
    loop: "{{username}}"  

  - name: install packages
    ansible.builtin.apt:
      name: "{{packages}}"
      state: present