---
#creating user
- hosts: localhost

  tasks:
   - name: creating a user account
     ansible.builtin.user:
       name: "{{ansible_user}}"
       uid: "{{ansible_uid}}"
       group: linux
       comment: "creating user account"
       shell: /bin/bash
       state: present

   - name: create a group for users
     ansible.builtin.group:
        name: "{{ansible_group}}"
        gid: "{{ansible_gid}}"
        state: present