---
# become su method playbook
- hosts: webserver
  
  vars:
    ansible_become: yes
    ansible_become_method:  su
    ansible_become_user: root
    ansible_become_password: "hello"
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "hello"

    tasks:
    - name: create a group
      ansible.bultin.group:
         name: IT_suppotrs
         gid: 100288